### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(V2p_gui)
add_subdirectory(V2p_guiContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    V2p_guiplugin
    V2p_guiContentplugin
    QtQuickDesignerComponents)